server:
  port: 8081

spring:
  application:
    name: it-gateway
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

zuul:
  routes:
    it-service: /it-service/**
  retryable: true

ribbon:
  ConnectTimeout: 130000
  ReadTimeout:  130000
  # 允许所有该服务的所有操作都可以重试
  OkToRetryOnAllOperations: true
  # 参与重试的服务个数（不包含第一个服务）  会重试所有存在服务
  MaxAutoRetriesNextServer: 3
  # 重试次数（不包含第一次请求）  且每次重试失败都会再次重试 所以8次是因为 1 * 2 + 3 * 2
#  MaxAutoRetries: 1
  # 没有 ribbon.retry.enable 这个配置 参考配置
  # spring.cloud.loadbalancer.retry.enabled 也不起作用
  # https://blog.csdn.net/chengqiuming/article/details/81336014
  # http://www.amd5.cn/atang_4466.html
#  retry:
#    enabled: true
  retryableStatusCodes: 500,502,503
