server:
  port: 8081

spring:
  application:
    name: it-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

zuul:
  routes:
    it-service: /it-service/**
  retryable: true

# ribbon配置会导致正常异常信息依然无限重试 8次
#ribbon:
#  ConnectTimeout: 130000
#  ReadTimeout:  130000
#  OkToRetryOnAllOperations: true # 允许所有该服务的所有操作都可以重试
#  MaxAutoRetriesNextServer: 3  # 参与重试的服务个数（不包含第一个服务）
#  MaxAutoRetries: 1 # 重试次数（不包含第一次请求）
#  retry:
#    enabled: true
#  retryableStatusCodes: 500,502,503