server:
  port: 8880

spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}
  instance:
    hostname: localhost
  server:
    # 提高缓存刷新率
    response-cache-update-interval-ms: 1000
    # 禁用缓存
    #use-read-only-response-cache: false
