server:
  port: 8082

spring:
  application:
    name: it-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

zuul:
  routes:
    it-service: /it-service/**
  retryable: true

ribbon:
  ConnectTimeout: 130000
  ReadTimeout: 130000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 3
  retryableStatusCodes: 500,502,503
  ServerListRefreshInterval: 1000
