server:
  port: 8884

spring:
  application:
    name: it-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8879/eureka/
  instance:
    hostname: localhost
    metadata-map:
      zone: ap
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 5