server:
  port: 8881

spring:
  application:
    name: it-service

eureka:
  datacenter: ap
  client:
    # 指定各个区域中所包含的eureka server地址
    # 一个region中可以包含多个zone,一个zone中可以包含多个eureka server
    # AWS
    # 优先连接sa1,若连接不上再连接sa2,再连不上，连接defaultZone，但是启动前两个连接会报错，不影响使用
    service-url:
      defaultZone: http://localhost:8879/eureka/
#      sa1: http://localhost:8879/eureka
#      sa2: http://localhost:8880/eureka
  instance:
#    hostname: localhost
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 5
    #属于哪一个zone
    metadata-map:
      zone: 81